// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA-mdHez5bNUSlahuCikuu9Ma-5ACYEok',
    appId: '1:357070245031:web:b0a833ee9c2d54f4a01f82',
    messagingSenderId: '357070245031',
    projectId: 'readap-fb5bf',
    authDomain: 'readap-fb5bf.firebaseapp.com',
    storageBucket: 'readap-fb5bf.appspot.com',
    measurementId: 'G-4CKP667DRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvQSBeAX4G2mAvxJCrMwiJclnpbI04y94',
    appId: '1:357070245031:android:49f2d7e424ef8386a01f82',
    messagingSenderId: '357070245031',
    projectId: 'readap-fb5bf',
    storageBucket: 'readap-fb5bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOKjo-QviENZ98TSFi8AhSv-nVQ67MeeE',
    appId: '1:357070245031:ios:118e1cef273c5d1ca01f82',
    messagingSenderId: '357070245031',
    projectId: 'readap-fb5bf',
    storageBucket: 'readap-fb5bf.appspot.com',
    iosBundleId: 'com.example.readap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOKjo-QviENZ98TSFi8AhSv-nVQ67MeeE',
    appId: '1:357070245031:ios:118e1cef273c5d1ca01f82',
    messagingSenderId: '357070245031',
    projectId: 'readap-fb5bf',
    storageBucket: 'readap-fb5bf.appspot.com',
    iosBundleId: 'com.example.readap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA-mdHez5bNUSlahuCikuu9Ma-5ACYEok',
    appId: '1:357070245031:web:422a94a5dca14f33a01f82',
    messagingSenderId: '357070245031',
    projectId: 'readap-fb5bf',
    authDomain: 'readap-fb5bf.firebaseapp.com',
    storageBucket: 'readap-fb5bf.appspot.com',
    measurementId: 'G-KE33C6Z251',
  );
}
